version: "3.7"
services:
  app:
    build:
      args:
        user: $USER
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tslol/tristanlol
    container_name: tristanlol
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tristanlol
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - tristanlol
networks:
  tristanlol:
    driver: bridge